config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :belge_categories


  post 'accept_booking', to: "bookings#accept"
  post 'refus_booking', to: "bookings#refus"

  resources :belges do
    resources :reviews
    resources :bookings
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get 'dashboard', to: 'profils#dashboard'
  mount Attachinary::Engine => "/attachinary"

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/belge.rb
class Belge < ApplicationRecord
  belongs_to :user
  has_many :belge_categories
  has_many :reviews
  has_many :bookings
  has_many :categories, through: :belge_categories
  has_attachment :photo

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/belge_category.rb
class BelgeCategory < ApplicationRecord
  belongs_to :category
  belongs_to :belge
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :belge
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :belge_categories
  has_many :belges, through: :belge_categories
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :belge
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  after_create :subscribe_to_newsletter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :bookings
  has_many :reviews
  has_many :belges, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
  user_params = auth.slice(:provider, :uid)
  user_params.merge! auth.info.slice(:email, :first_name, :last_name)
  user_params[:facebook_picture_url] = auth.info.image
  user_params[:token] = auth.credentials.token
  user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
  user_params = user_params.to_h

  user = User.find_by(provider: auth.provider, uid: auth.uid)
  user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
  if user
    user.update(user_params)
  else
    user = User.new(user_params)
    user.password = Devise.friendly_token[0,20]  # Fake password for validation
    user.save
  end

  return user
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/belges_controller.rb
class BelgesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_belge, only: [:show, :edit]
  def index

    # if params["accent"]
    #   category = Category.where(name: params[:accent])
    #   @belges = BelgeCategory.where(category: category).map { |cat| cat.belge }
    # else
    #   @belges = Belge.where.not(latitude: nil, longitude: nil)
    # end

    if params[:city] != ''
      @belges = Belge.near(params[:city], 10)
    else
      @belges = Belge.where.not(latitude: nil, longitude: nil)
    end

    @hash = Gmaps4rails.build_markers(@belges) do |belge, marker|
      marker.lat belge.latitude
      marker.lng belge.longitude
      marker.infowindow belge.first_name + " " + belge.last_name
    end
  end

  def show
    @belge_coordinates = { lat: @belge.latitude, lng: @belge.longitude }
    @booking = Booking.new
  end

  def new
    @belge = Belge.new
  end

  def create
    @belge = Belge.new(belge_params)
    @belge.user = current_user
    if @belge.save
      BelgeMailer.creation_confirmation(@belge).deliver_now
      redirect_to belge_path(@belge)
    else
      render :new
    end
  end

  # def edit

  # end

  # def update
  #   @belge.user = current_user
  #   if @belge.user.update(belge_params)
  #       redirect_to belge_path(@belge)
  #      else
  #       render :new
  #     end
  # end


  private

  def set_belge
    @belge = Belge.find(params[:id])
  end

  def belge_params
    params.require(:belge).permit(:first_name, :last_name, :description, :photo, :price, :address, :user_id, belge_category_ids: [] )
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
  end

  def index
    @bookings = Booking.all
  end

  def new
    @belge = Belge.find(params[:belge_id])
    @booking = Booking.new
  end

  def create
    @belge = Belge.find(params[:belge_id])
    @booking = Booking.new(booking_params)
    @booking.belge = Belge.find(params[:belge_id])
    @booking.user = current_user
      if @booking.save
        redirect_to dashboard_path
      else
        render :new
      end
  end

  def edit
    @belge = Belge.find(params[:belge_id])
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path
  end

  def accept
    id = params[:id].to_i
    Booking.find(id).update_attribute(:status, 'Demande acceptée')
    redirect_back(fallback_location: root_path)
  end

  def refus
    id = params[:id].to_i
    Booking.find(id).update_attribute(:status, 'Demande rejetée')
    redirect_back(fallback_location: root_path)
  end

    private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :message, :belge_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @belges = Belge.order("RANDOM()").first(4)
  end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  def dashboard
    @bookings = current_user.bookings
    @belges = current_user.belges
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def index
  #   @review = Review.all
  # end

  # def show
  # end

  def new
    @belge = Belge.find(params[:belge_id])
    @review = Review.new
  end

  def create
    @belge = Belge.find(params[:belge_id])
    @review = Review.new(review_params)
    @review.belge = Belge.find(params[:belge_id])
    @review.user = current_user
      if @review.save
        redirect_to belge_path(@belge)
      else
        render :new
      end
  end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

  private

  def review_params
    params.require(:review).permit(:title, :description, :rating, :belge_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/belges/_card.html.erb
    <div class="card" style="background-image: linear-gradient(rgba(51,51,51,0.3), rgba(51,51,51,0.7)), url( '<% if belge.photo? %> <%= cl_image_path belge.photo.path %> <% end %>');">
      <div class="card-category"></div>
      <div class="card-description">
        <h2><%= belge.first_name %> <%= belge.last_name %></h2>
      </div>
      <div class="card-price"> <p><%= belge.price %> €</p> </div>
      <%= link_to nil, belge_path(belge), class: 'card-link' %>
    </div>

app/views/belges/_form.html.erb
<%= simple_form_for @belge do |f| %>
  <br>
  <h2 class="text-center">Créer un belge</h2>
  <br>
  <br>
  <div class="row">
    <div class="col-xs-6">
      <div class="form-group">
        <%= f.input :first_name, class: 'form-control'%>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="form-group">
        <%= f.input :last_name, class: 'form-control'%>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.input :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.input :address, class: 'form-control', input_html: { id: 'inlineFormInput', name: 'city' } %>
  </div>
  <div class="form-group">
    <%= f.input :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.association :belge_categories, collection: Category.all, as: :check_boxes, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.input :photo, as: :attachinary %>
  </div>
  <br>
  <div class="form-group">
    <%= f.button :submit, class: "btn btn-danger form-control", value: "Enregistrer" %>
  </div>
  <div class="form-group">
    <%= link_to 'Annuler', belges_path, class: "btn btn-default form-control" %>
  </div>
<% end %>

app/views/belges/create.html.erb
<h1>Belges#create</h1>
<p>Find me in app/views/belges/create.html.erb</p>

app/views/belges/destroy.html.erb
<h1>Belges#destroy</h1>
<p>Find me in app/views/belges/destroy.html.erb</p>

app/views/belges/edit.html.erb
<h1>Belges#edit</h1>
<p>Find me in app/views/belges/edit.html.erb</p>

app/views/belges/index.html.erb
<div class="map-layout">
  <div class="cards_container">
    <div class="row">
      <div class="col-xs-12">
        <form class="form-inline form-in-show text-center" action='belges' autocomplete="on">
          <input type="text" class="form-control" id="inlineFormInput" name="city" placeholder="Search by city">
          <!-- <select class="form-control" name="accent">
            <option value="accent Bruxelles">Accent de Bruxelles</option>
            <option value="accent de Charleroi">Accent de Charleroi</option>
            <option value="accent de Namur">Accent de Namur</option>
          </select> -->
          <button type="submit" class="btn btn-danger">Search</button>
        </form>
      </div>
    </div>
    <% if @belges.blank? %>
    <div class="error"><h3>Oops, there are no Belgians in this city yet.</h3></div>
    <div class="img-error"><img src="http://res.cloudinary.com/copas/image/upload/v1503060121/lost1_pnesfq.jpg"></div>
    <% end %>
    <div class="row">
      <% @belges.each do |belge| %>
      <div class="col-xs-6 col-sm-3 col-md-3">
        <%= render 'card', belge: belge  %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="map-container">
    <div id="map"></div>
  </div>
</div>
<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).ready(function() {
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
});
<% end %>
<% end %>

app/views/belges/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/belges/show.html.erb
<div class="container text-center">
  <br>
  <br>
  <br>
  <div class="grid-presentation">


    <div class="belge-presentation">
      <div class="belge-name">
        <h3 class="text-right"><strong><%= @belge.first_name %> <%= @belge.last_name %></strong></h3>
      </div>
      <div class="belge-address">
        <p class="text-right"><%= @belge.address %></p>
      </div>
      <div class="belge-description">
        <p class="text-right"><strong>Présentation</strong></p>
        <p class="text-right"><%= @belge.description %> "</p>
      </div>
    </div>
    <div class="belge-avatar gradient">
      <% if @belge.photo? %>
        <%= cl_image_tag @belge.photo.path, width: 350, height: 350, crop: :fill %>
      <% end %>
    </div>

    <div class="midle-navbar">
      <p></p>
    </div>


    <div class="total-price">
      <div class="ttc">
        <p class="text-right">Prix TTC : </p>
      </div>
      <div class="price">
        <p class="text-left"><strong><%= @belge.price %> €/jour</strong></p>
      </div>
    </div>


    <div class="review">
      <div class="title-review-list">
        <h3 class="text-left">Reviews</h3>
      </div>
        <div class="form-group">
          <% @belge.reviews.each do |review| %>
            <div class="article">
              <div class="header-reviews">
                <div class="left">
                  <%= cl_image_tag review.user.facebook_picture_url, width: 40, height: 40, crop: :fill, radius: 50, class: "avatar-little"%>
                  <div class="user-name">
                    <p class="text-left"><strong><%=review.user.first_name%> <%=review.user.last_name%></strong></p>
                    <p class="text-left"><%= review.created_at %></p>
                  </div>
                </div>
                <div>
                  <div class="article-rating">
                    <% review.rating.times do %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    <%  end %>
                    <% (5 - review.rating).times do %>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                    <%  end %>
                  </div>
                </div>
              </div>
              <div class="toto">
                <p class="text-left"><%= review.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>


    <div class="reservation">
      <div class="title_reservation">
        <h4>Réserver maintenant</h4>
        <div class="form-group">
          <%= simple_form_for [@belge, @booking] do |f| %>
            <%= f.input :start_date, as: :date, html5: true, class: 'form-control'  %>
            <%= f.input :end_date, as: :date, html5: true, class: 'form-control'  %>
            <%= f.input :message, class: 'form-control' %>
            <%= f.button :submit, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/belges/update.html.erb
<h1>Belges#update</h1>
<p>Find me in app/views/belges/update.html.erb</p>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<%= simple_form_for [@belge, @booking] do |f| %>
  <%= f.input :status, collection: ["Demande acceptée", "Demande rejetée"] %>
  <%= f.button :submit %>
  <% end %>

app/views/bookings/index.html.erb
<p>All bookings : </p>

<% @bookings.each do |booking| %>
  <p><%= booking.start_date %></p>
  <p><%= booking.end_date %></p>
  <p><%= booking.message %></p>
  <p><%= booking.status %></p>
  <% end %>

app/views/bookings/new.html.erb
<h1>Faire une demande de book avec un Dikkechecker</h1>



<%= simple_form_for [@belge, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.input :message %>
  <%= f.button :submit %>
  <% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

<%= @booking.belge %>
<%= @booking.message %>
<%= @booking.start_date %>
<%= @booking.end_date %>
<%= @booking.belge.price %>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ou tu sors, ou j'te sors</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag "application" %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(255,255,255,0.6) 0%, rgba(255,255,255,0.3) 50%), url('https://www.streetpress.com/sites/default/files/field/image/olivier-von-hoffstadt-damiens-cover4.jpg');">
  <div class="banner-content">
    <div>
      <%= image_tag "logo_white.png", id: "logo"%>
    </div>
    <div>
      <%= image_tag "logo_text_white.png", id: "logo_text"%>
    </div>
    <p>Rent a Belgian to spend a wonderful evening </p>
    <form class="form-inline" action='belges' autocomplete="on">
      <label class="sr-only" for="inlineFormInput"></label>
      <input type="text" class="form-control mb-2 mr-sm-2 mb-sm-0 input-lg" id="inlineFormInput" name="city" placeholder="Search by city">
      <button type="submit" class="btn btn-danger btn-lg">Search</button>
    </form>
  </div>
</div>
<div class="container">
<br>
<br>
<h1 class="text-center">Les belges les plus demandés</h1>
<br>
<br>
  <div class="row">
    <% @belges.each do |belge| %>
      <%= render 'shared/card', belge: belge %>
    <% end %>
  </div>
</div>

app/views/profils/dashboard.html.erb
<div class="profile-header-wrapper">
  <div class="container profile-header-container text-center">
    <div class="profile-header-infos">
      <h2>
      My Dashboard
      </h2>
      <br>
    </div>
    <div class="tabs">
      <a class="tab active" data-target="#bio">
        <h3>
        Mes reservations
        </h3>
      </a>
      <a class="tab" data-target="#projects">
        <h3>
        Mes dikkecheckers
        </h3>
      </a>
    </div>
  </div>
</div>
<div class="container text-center dash" >
  <div class="tab-content" id="bio">
    <div class="container">
      <br>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <br>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <% @bookings.each do |booking| %>
            <div class="row">
              <div class="message">
                <% if booking.belge.photo %>
                <%= cl_image_tag booking.belge.photo.path, width: 50, height: 50, crop: :fill, radius: 100%>
                <% end %>
                <div class="message-name text-center">
                  <h4>
                  <%= booking.belge.first_name %> <%= booking.belge.last_name %>
                  </h4>
                </div>
                <div class="message-body">
                  <p>
                    <%= booking.start_date %> - <%= booking.end_date %>
                  </p>
                </div>
                <div class="message-status">
                  <p>
                    <%= booking.status %>
                  </p>
                  <% if booking.status == "Demande acceptée" %>
                  <%= link_to "Add review", new_belge_review_path(booking.belge),  class: "btn btn-danger btn-review" %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-content hidden" id="projects">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <% @belges.each do |belge| %>
      <br>
      <h3>
      <%= belge.first_name %> <%= belge.last_name %>
      </h3>
      <% if belge.bookings.blank? %>
      <div class="message"><p> <em>Pas de réservation, ton dikkechekker n'a pas de succès...</em></p></div>
      <% end %>
      <% belge.bookings.each do |booking| %>
      <div class="row">
        <div class="message">
          <%= cl_image_tag booking.user.facebook_picture_url, class: "avatar-large"%>
          <div class="message-name text-center">
            <h4><%=booking.user.first_name%> <%=booking.user.last_name%></h4>
          </div>
          <div class="message-body">
            <p>Dates : <%= booking.start_date %> to <%= booking.end_date %></p>
          </div>
          <div class="message-status">
            <% if booking.status == "Demande en cours" %>
            <%= link_to "Refus", refus_booking_path(id: booking.id), :method => :post, class: 'btn btn-default' %>
            <%= link_to "Accept", accept_booking_path(id: booking.id), :method => :post, class: 'btn btn-danger' %>
            <% else %>
            <%= booking.status %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <br>
      <br>
      <h2 class="text-center">Add a review</h2>
      <br>
      <br>
      <%= simple_form_for [@belge, @review] do |f| %>
        <div class="form-group">
          <%= f.input :title %>
        </div>
        <div class="form-group">
          <%= f.input :description %>
        </div>
        <div class="form-group">
          <%= f.input :rating, collection: (1..5).to_a %>
        </div>
        <br>
        <div class="form-group">
          <%= f.button :submit, "Save", class: 'btn btn-danger form-control' %>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_card.html.erb
  <div class="col-xs-6 col-sm-3">
    <div class="card" style="background-image: linear-gradient(rgba(51,51,51,0.3), rgba(51,51,51,0.7)), url( '<% if belge.photo? %> <%= cl_image_path belge.photo.path %> <% end %>');">
      <div class="card-category"></div>
      <div class="card-description">
        <h2><%= belge.first_name %> <%= belge.last_name %></h2>
      </div>
      <div class="card-price"> <p><%= belge.price %> €</p> </div>
      <%= link_to nil, belge_path(belge), class: 'card-link' %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible elementToFadeInAndOut hidden" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible elementToFadeInAndOut hidden" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    DIKKECHECK is a project made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_text_black.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Devenez Dikkechecker", new_belge_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Tableau de bord", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Sign in"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>